import { compositionsById } from "@workspace/compositions/registry";
import type { CompositionCategory } from "@workspace/compositions/schema";
import { tool } from "ai";
import { z } from "zod";
import { KNOWN_CATEGORIES, listScenesInCategory } from "./catalog";

/**
 * Two-track tool surface for the studio agent:
 *
 *   PRIMARY (one-shot generation): `buildProject` takes a complete Project
 *   JSON matching the studio's import schema and loads it via LOAD_PROJECT.
 *   This is what the agent calls when the user asks for a fresh video.
 *
 *   SURGICAL (edits): `addClip`, `updateClipProps`, `updateClipStyle`,
 *   `updateClipDuration`, `deleteClip`, `clearProject`, `listClips`. These
 *   mutate the existing timeline one operation at a time. The agent
 *   reaches for them when the user says "tweak", "swap", "remove that",
 *   etc. — preserving the user's manual changes.
 *
 *   DISCOVERY: `listScenes` and `getSceneDetails` exist as fallback for
 *   the few cases where the inline catalog in the system prompt isn't
 *   enough (or when the user adds a new composition mid-session).
 *
 * Server-executed tools have an `execute` here; client-executed tools
 * have only a schema and run inside AgentPanel's `onToolCall` so they
 * can dispatch into the studio reducer.
 */

// Project JSON schema — mirrors `parseProjectJson` in features/studio/lib/project-io.ts.
const ClipStyleSchema = z
  .object({
    background: z.string().optional(),
    color: z.string().optional(),
    fontFamily: z.string().optional(),
    accent: z.string().optional(),
  })
  .partial();

const SceneTransitionSchema = z
  .object({
    kind: z.string(),
    durationInFrames: z.number().int().min(0).optional(),
  })
  .passthrough();

const ClipSchema = z.object({
  id: z
    .string()
    .min(1)
    .describe(
      "Stable unique id within the project. Use kebab/uuid style — generated by the agent.",
    ),
  compositionId: z
    .string()
    .min(1)
    .describe("PascalCase composition id from the catalog (e.g. 'TitlePopup')"),
  props: z
    .record(z.string(), z.unknown())
    .describe(
      "FULL props object. Start from the composition's defaultProps in the catalog and override only the fields you want to change.",
    ),
  durationInFrames: z.number().int().min(15).optional(),
  style: ClipStyleSchema.optional(),
  transition: SceneTransitionSchema.optional(),
});

const ProjectSchema = z.object({
  fps: z.number().int().min(1),
  width: z.number().int().min(1),
  height: z.number().int().min(1),
  clips: z.array(ClipSchema).min(1),
  defaultTransition: SceneTransitionSchema.optional(),
});

export const tools = {
  // ───── PRIMARY one-shot generation ────────────────────────────────────
  buildProject: tool({
    description:
      "Replace the entire timeline with a new video. Pass a complete Project JSON matching the studio's import schema. Use this when the user asks for a fresh video. Atomic: either the whole project loads or nothing does.",
    inputSchema: z.object({
      project: ProjectSchema.describe(
        "The complete Project JSON. Must include fps, width, height, and a non-empty clips array. Each clip needs id, compositionId, and props.",
      ),
    }),
    // No execute — runs client-side in AgentPanel.onToolCall.
  }),

  // ───── DISCOVERY (category → scenes → details funnel) ────────────────
  // The system prompt lists categories. The agent calls
  // `listScenesInCategory` to drill in, then `getSceneDetails` for the
  // few scenes it wants to use. This keeps the prompt constant-size as
  // the registry grows.
  listScenesInCategory: tool({
    description:
      "Returns every scene in a category as `{ id, title, description, durationInFrames, fps, width, height, brandLocked }`. Call this for each category that fits the user's brief; then call getSceneDetails for the scenes you actually want to build with.",
    inputSchema: z.object({
      category: z
        .enum(
          KNOWN_CATEGORIES as [CompositionCategory, ...CompositionCategory[]],
        )
        .describe(
          "One of the category slugs from the prompt: text, social, data, devtools, marketing, layout, captions, media.",
        ),
    }),
    execute: async ({ category }) => ({
      category,
      scenes: listScenesInCategory(category),
    }),
  }),

  getSceneDetails: tool({
    description:
      "Returns the full defaultProps and field schema for one composition. Call this for every scene you plan to use in buildProject so your props match the actual schema instead of being invented.",
    inputSchema: z.object({
      compositionId: z.string(),
    }),
    execute: async ({ compositionId }) => {
      const info = compositionsById[compositionId];
      if (!info) return { error: `Unknown composition id: ${compositionId}` };
      return {
        id: info.id,
        title: info.title,
        description: info.description,
        category: info.category,
        brandLocked: info.brandMode === "locked",
        defaultProps: info.defaultProps,
        fields: info.fields,
      };
    },
  }),

  // ───── SURGICAL edits (client-executed) ───────────────────────────────
  listClips: tool({
    description:
      "Read the current timeline. Returns clips in order with id, compositionId, durationInFrames, props, and style. Call this before any surgical edit so you reference the right clipIds.",
    inputSchema: z.object({}),
  }),

  clearProject: tool({
    description: "Remove every clip from the timeline.",
    inputSchema: z.object({}),
  }),

  addClip: tool({
    description:
      "Append a new clip to the timeline. Returns the new clipId. Prefer buildProject for full-project generation; use addClip only for incremental additions to an existing timeline.",
    inputSchema: z.object({
      compositionId: z.string(),
    }),
  }),

  updateClipProps: tool({
    description:
      "Replace a clip's props with new values. Pass the FULL props object — this is a replace, not a patch. Look up the clip's current props with listClips first and merge.",
    inputSchema: z.object({
      clipId: z.string(),
      props: z.record(z.string(), z.unknown()),
    }),
  }),

  updateClipStyle: tool({
    description:
      "Change a clip's universal style (background, color, fontFamily, accent). Any omitted field is left untouched. Empty string clears the override. No effect on brand-locked scenes.",
    inputSchema: z.object({
      clipId: z.string(),
      background: z.string().optional(),
      color: z.string().optional(),
      fontFamily: z.string().optional(),
      accent: z.string().optional(),
    }),
  }),

  updateClipDuration: tool({
    description:
      "Set how many frames a clip plays for. 30fps → 90 frames = 3 seconds.",
    inputSchema: z.object({
      clipId: z.string(),
      durationInFrames: z.number().int().min(15),
    }),
  }),

  deleteClip: tool({
    description: "Remove one clip from the timeline by id.",
    inputSchema: z.object({
      clipId: z.string(),
    }),
  }),
};

export type AgentTools = typeof tools;
