#!/usr/bin/env node
/**
 * Reads every composition's source files and emits a static TypeScript
 * module mapping `<id>` → `{ component, meta }` source strings. The Docs
 * page imports this file to render the Source block client-side without
 * touching Node fs at runtime.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");
const compositionsDir = join(repoRoot, "apps", "remotion", "src", "compositions");

const entries = [];

// Collect `<Name>/<Name>.tsx` composition folders. A folder without a
// same-named component (e.g. the `backgrounds/` grouping dir) is recursed into
// one level so grouped categories are picked up too. Underscore/dot-prefixed
// dirs (helpers like `_chat-demo`) are skipped.
function collect(dir) {
  for (const name of readdirSync(dir)) {
    if (name.startsWith("_") || name.startsWith(".")) continue;
    const full = join(dir, name);
    if (!statSync(full).isDirectory()) continue;
    let component = "";
    try {
      component = readFileSync(join(full, `${name}.tsx`), "utf-8");
    } catch {
      collect(full); // grouping dir (no same-named .tsx) — descend one level
      continue;
    }
    let meta = "";
    try {
      meta = readFileSync(join(full, "meta.ts"), "utf-8");
    } catch {
      meta = "";
    }
    entries.push({ id: name, component, meta });
  }
}

collect(compositionsDir);

const banner = `// AUTO-GENERATED by scripts/generate-sources.mjs. Do not edit by hand.\n// Re-run: bun run --cwd apps/web sources\n// biome-ignore-all lint/suspicious/noArrayIndexKey: source code stored as strings; lints don't apply\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: source code stored as strings; lints don't apply\n\n`;
const body = entries
  .map(
    (e) => `  ${JSON.stringify(e.id)}: {\n    component: ${JSON.stringify(e.component)},\n    meta: ${JSON.stringify(e.meta)},\n  },`,
  )
  .join("\n");

const out = `${banner}export type CompositionSource = {\n  component: string;\n  meta: string;\n};\n\nexport const compositionSources: Record<string, CompositionSource> = {\n${body}\n};\n`;

const target = join(repoRoot, "apps", "web", "lib", "generated-sources.ts");
writeFileSync(target, out, "utf-8");
console.log(`Wrote ${entries.length} source entries → ${target}`);
